### ISSUE TITLE
License choice checklist

### ISSUE THREAD

**Issue by karanpreetkaur** [UBC-MDS/py_outliers_utils#55]

**Comment by karanpreetkaur** [comment]
Setting up this issue for discussion of if we should change our licensing in our Python and R issue. Feel free to leave your thoughts and discuss.

**Comment by karanpreetkaur** [comment]
Having taken a look at the lecture 8 material and as discussed with @lipcai  and @scarlqq on the call yesterday, we are going to stick with the MIT license.

Since our package seems more for our own purposes of software development and workflows conceptual understanding MIT seems to fit what we require according to https://choosealicense.com. People can do what they want with it, but we have limitation of liability.

To opt MIT license for our package , we have added contributor's name already.

**Comment by scarlqq** [comment]
We all agree with this. Considering the purpose of our package, MIT license should be exactly what we need.

**Comment by lipcai** [comment]
We all agree with this. Considering the purpose of our package, MIT license should be exactly what we need.

**Comment by karanpreetkaur** [comment]
Thanks for the discussion @lipcai @scarlqq. Looking at your comments to go with existing MIT license, I'm closing this issue
